[package]
name = "stark"
version = "0.2.0-dev"
authors = ["Matthew Rothlisberger <mattjrothlis@gmail.com>"]
edition = "2021"

[features]
memdbg = []
stkdbg = []

[dependencies]
winit = { path = "../winit" }
gfx-hal = { path = "../gfx/src/hal" }

raw-window-handle = "0.3"
shaderc = "0.7.3"

png = "0.17.2"
ttf-parser = "0.13.3"

# Change graphics backend with
# tools/g-api.sh <backend>

# DO NOT ALTER BY HAND
[dependencies.backend]
package = "gfx-backend-vulkan"
path = "../gfx/src/backend/vulkan"
# KEEP AT END OF FILE
log = "0.4.14"
simple_logger = "1.16.0"
