[package]
name = "stark"
version = "0.1.0"
authors = ["Matthew Rothlisberger <mattjrothlis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
memdbg = []
stkdbg = []

[dependencies]
winit = { path = "../winit" }
gfx-hal = { path = "../gfx/src/hal" }

png = "0.16.7"
raw-window-handle = "0.3.3"
shaderc = "0.6.3"

log = "0.4.11"
simple_logger = "1.11.0"

# [target.'cfg(target_os = "macos")'.dependencies.backend]
# package = "gfx-backend-metal"
# path = "../gfx/src/backend/metal"

# [target.'cfg(windows)'.dependencies.backend]
# package = "gfx-backend-dx12"
# path = "../gfx/src/backend/dx12"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.backend]
package = "gfx-backend-vulkan"
path = "../gfx/src/backend/vulkan"