[package]
name = "stark"
version = "0.1.0"
authors = ["Matthew Rothlisberger <mattjrothlis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { path = "../winit" }
gfx-hal = { path = "../gfx/src/hal" }

png = "0.16.7"

log = "0.4.11"
simple_logger = "1.11.0"

[target.'cfg(target_os = "macos")'.dependencies.backend]
package = "gfx-backend-metal"
version = "0.6.4"

[target.'cfg(windows)'.dependencies.backend]
package = "gfx-backend-dx12"
version = "0.6.11"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies.backend]
package = "gfx-backend-vulkan"
version = "0.6.5"