[package]
name = "stark"
version = "0.2.0-dev"
authors = ["Matthew Rothlisberger <mattjrothlis@gmail.com>"]
edition = "2021"

[features]
memdbg = []
stkdbg = []

[dependencies]
winit = { path = "../winit" }

ash = { version = "0.35.0", features = ["linked"] }
ash-window = "0.9.0"
raw-window-handle = "0.3"
shaderc = "0.7.3"

png = "0.17.2"
ttf-parser = "0.13.3"

log = "0.4.14"
simple_logger = "1.16.0"