# SPDX-FileCopyrightText: © 2021 Matthew Rothlisberger
# SPDX-License-Identifier: CC0-1.0

[toolchain]
channel = "nightly"
# targets = [ "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc" ]
profile = "default"
